apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark.name" . }}-role
  namespace: {{ .Values.project.namespace }}
  labels:
    {{- include "spark.commonLabels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark.name" . }}-role-binding
  namespace: {{ .Values.project.namespace }}
  labels:
    {{- include "spark.commonLabels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: {{ include "spark.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
