

apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.name" . }}
  namespace: {{ .Values.project.namespace }}
  labels:
        {{- include "spark.commonLabels" . | indent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.services.driver.type }}
  selector:
        {{- include "spark.selectorLabels" . | indent 4 }}
    spark.driver: {{ include "spark.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.driver.port }}
      targetPort: {{ .Values.services.driver.port }}
      name: driver-port
    - protocol: TCP
      port: {{ .Values.services.ui.port }}
      targetPort: {{ .Values.services.ui.port }}
      name: ui-port